[tool.poetry]
name = "pyenigma-api"
version = "0.1.0"
description = ""
authors = ["arwindersngh62 <arwindersngh62@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
